version: "3.8"

services:
  nginx-proxy:
    image: jwilder/nginx-proxy:latest
    container_name: nginx-proxy
    ports:
      - "80:80"              # only HTTP
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
      - webnet

  static-site:
    build:
      context: .             # assumes Dockerfile & dist/ live here
      dockerfile: Dockerfile
    image: coderra-static:latest
    container_name: coderra-website
    environment:
      - VIRTUAL_HOST=localhost, coderra.je
    expose:
      - "80"                 # visible only to the proxy, not host
    networks:
      - webnet

networks:
  webnet:
    driver: bridge
