name: coderra
region: nyc
static_sites:
  - name: web
    github:
      repo: jgalan247/coderraje
      branch: main
      deploy_on_push: true
    source_dir: /public
    catchall_document: index.html
    error_document: 404.html
